Import library numpy.

In [3]:
import numpy as np

The main data structure is a massive. Massive looks like a list, but include in only one type of data like int or float. With massive you can easier and faster calculate result.

For creating massive use method `.array()`.

In [5]:
massive = np.array([1, 2, 3, 4], float)

massive

array([1., 2., 3., 4.])

In [6]:
type(massive)

numpy.ndarray

The first argument is a list of elements, the second is a type of elements. You can use indexes of the ceated structure as a list.

In [12]:
print(massive[3])

massive[-2:]

4.0


array([3., 4.])

Massive can be a multidimensional.

In [16]:
massive_two = np.array([[1, 2, 3, 4], [8, 7, 6, 5]], float)

print(massive_two[1, 2])

massive_two

6.0


array([[1., 2., 3., 4.],
       [8., 7., 6., 5.]])

In [35]:
massive_two[-1:, 0] # one argument is measurement, second - elements.
massive_two[0, -1:]

array([4.])

Attribute `.shape` - returns dimension.

In [37]:
massive_two.shape

(2, 4)

Attribute `.dtype` - returns type of the elements.

In [38]:
massive_two.dtype

dtype('float64')

Method `.len()` returns size of first dimension of massive.

In [39]:
len(massive_two)

2

Operator `in` used for check element in massive.

In [40]:
666 in massive_two

False

Method `.reshape()` used for change massive dimension.

In [46]:
massive_two = massive_two.reshape((4, 2))

print(massive_two.shape)

massive_two

(4, 2)


array([[1., 2.],
       [3., 4.],
       [8., 7.],
       [6., 5.]])

For coping massive and not copy link use method `.copy()`.

In [48]:
massive_three = massive_two.copy()

massive_three

array([[1., 2.],
       [3., 4.],
       [8., 7.],
       [6., 5.]])

You can convert massive to list wiht method `tolist()`.

In [51]:
list_one = massive_three.tolist()

list_one

[[1.0, 2.0], [3.0, 4.0], [8.0, 7.0], [6.0, 5.0]]

For convert in human unreadable type use method `.tostring()`.

In [53]:
string_one = massive_two.tostring()

string_one

C:\Users\Deniz\AppData\Local\Temp\ipykernel_11412\752424615.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  string_one = massive_two.tostring()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x14@'

And negative method `.fromstring()` - return dimension.

In [57]:
massive_four = np.fromstring(string_one)

massive_four

C:\Users\Deniz\AppData\Local\Temp\ipykernel_11412\3070014062.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  massive_four = np.fromstring(string_one)


array([1., 2., 3., 4., 8., 7., 6., 5.])

For quick setting use method `.fill()`.

In [63]:
massive_five = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

massive_five.fill(5)

massive_five

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

For convert from multidimension to monodimension massiv use method `.flatten()`.

In [65]:
tmp_massive = np.array([[1, 2, 3,], [3, 2, 1]])

tmp_massive = tmp_massive.flatten()

tmp_massive

array([1, 2, 3, 3, 2, 1])

We can concatenate massive with method `.concatenate()`. Default axis is 0.

In [69]:
np.concatenate((tmp_massive, massive_five))

array([1, 2, 3, 3, 2, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5])

We can concatenate with by any axis.

In [75]:
a = np.array([[1, 2, 3], [6, 5, 4]])
b = np.array([[1, 2, 3], [6, 5, 4]])

print(np.concatenate((a, b), axis = 0))

np.concatenate((a, b), axis = 1)

[[1 2 3]
 [6 5 4]
 [1 2 3]
 [6 5 4]]


array([[1, 2, 3, 1, 2, 3],
       [6, 5, 4, 6, 5, 4]])

We can change shape of massive by attribute `.newaxis`.

In [79]:
last_massive = np.array([1, 2, 3], int)

last_massive

array([1, 2, 3])

In [84]:
last_massive[:, np.newaxis]

last_massive[:, np.newaxis].shape

(3, 1)